/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/peptideos/{id}": {
    get: operations["findById_1"];
    put: operations["update"];
    delete: operations["delete_1"];
  };
  "/organismos/{id}": {
    get: operations["findById_2"];
    put: operations["update_1"];
    delete: operations["delete_2"];
  };
  "/peptideos": {
    get: operations["findAll_1"];
    post: operations["save"];
  };
  "/organismos": {
    get: operations["findAll_2"];
    post: operations["create"];
  };
  "/publicacoes": {
    get: operations["findAll"];
  };
  "/publicacoes/{id}": {
    get: operations["findById"];
    delete: operations["delete"];
  };
  "/peptideos/tipoPeptideo/{tipoPeptideo}": {
    get: operations["findByTipoPeptideo"];
  };
  "/organismos/query": {
    get: operations["query"];
  };
  "/nomes-populares": {
    get: operations["findAll_3"];
  };
  "/nomes-populares/{id}": {
    get: operations["findById_3"];
    delete: operations["delete_3"];
  };
  "/funcoes-biologicas": {
    get: operations["findAll_4"];
  };
  "/funcoes-biologicas/{id}": {
    get: operations["findById_4"];
    delete: operations["delete_4"];
  };
  "/caso-sucesso": {
    get: operations["findAll_5"];
  };
  "/caso-sucesso/{id}": {
    get: operations["findById_5"];
    delete: operations["delete_5"];
  };
  "/caracteristicas-adicionais": {
    get: operations["findAll_6"];
  };
  "/caracteristicas-adicionais/{id}": {
    get: operations["findById_6"];
    delete: operations["delete_6"];
  };
  "/atividades-citotoxicas": {
    get: operations["findAll_7"];
  };
  "/atividades-citotoxicas/{id}": {
    get: operations["findById_7"];
    delete: operations["delete_7"];
  };
  "/atividades-antifungicas": {
    get: operations["findAll_8"];
  };
  "/atividades-antifungicas/{id}": {
    get: operations["findById_8"];
    delete: operations["delete_8"];
  };
  "/atividades-antibacterianas": {
    get: operations["findAll_9"];
  };
  "/atividades-antibacterianas/{id}": {
    get: operations["findById_9"];
    delete: operations["delete_9"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AtivAntibacterianaDTO: {
      /** Format: int64 */
      id?: number;
      descricao?: string;
    };
    AtivAntifungicaDTO: {
      /** Format: int64 */
      id?: number;
      descricao?: string;
    };
    AtivCitotoxicaDTO: {
      /** Format: int64 */
      id?: number;
      descricao?: string;
    };
    CaracterisAdicionaisDTO: {
      /** Format: int64 */
      id?: number;
      descricao?: string;
    };
    CasoSucessoDTO: {
      /** Format: int64 */
      id?: number;
      caso?: string;
    };
    FuncBiologicaDTO: {
      /** Format: int64 */
      id?: number;
      descricao?: string;
    };
    PeptideoDTO: {
      /** Format: int64 */
      id?: number;
      peptideo?: string;
      /** Format: int32 */
      quantidadeAminoacidos?: number;
      /** @enum {string} */
      tipoPeptideo?: "SINTETIZADO" | "NATURAL";
      sequencia?: string;
      estruturaTridimensional?: string;
      /** Format: double */
      massaMolecular?: number;
      /** Format: double */
      impedimentoEsterico?: number;
      /** Format: double */
      hidrofobicidade?: number;
      /** Format: double */
      hidrofibocidade?: number;
      /** Format: double */
      pontoIsoeletrico?: number;
      /** Format: double */
      hidropatia?: number;
      /** Format: double */
      anfipaticidade?: number;
      /** Format: double */
      hidrofilicidade?: number;
      /** Format: int32 */
      cargaLiquidaTotal?: number;
      /** Format: double */
      indiceBoman?: number;
      descricao?: string;
      funcBiologicas?: components["schemas"]["FuncBiologicaDTO"][];
      ativAntibacterianas?: components["schemas"]["AtivAntibacterianaDTO"][];
      ativAntifungicas?: components["schemas"]["AtivAntifungicaDTO"][];
      ativCitotoxicas?: components["schemas"]["AtivCitotoxicaDTO"][];
      casosSucesso?: components["schemas"]["CasoSucessoDTO"][];
      caracterisAdicionais?: components["schemas"]["CaracterisAdicionaisDTO"][];
      publicacoes?: components["schemas"]["PublicacaoDTO"][];
    };
    PublicacaoDTO: {
      /** Format: int64 */
      id?: number;
      url?: string;
    };
    NomePopularDTO: {
      /** Format: int64 */
      id?: number;
      nome?: string;
    };
    OrganismoDTO: {
      /** Format: int64 */
      id?: number;
      especie?: string;
      origem?: string;
      familia?: string;
      nomeCientifico?: string;
      nomesPopulares?: components["schemas"]["NomePopularDTO"][];
      peptideos?: components["schemas"]["PeptideoDTO"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  findById_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PeptideoDTO"];
        };
      };
    };
  };
  update: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PeptideoDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PeptideoDTO"];
        };
      };
    };
  };
  delete_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  findById_2: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrganismoDTO"];
        };
      };
    };
  };
  update_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganismoDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrganismoDTO"];
        };
      };
    };
  };
  delete_2: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  findAll_1: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PeptideoDTO"][];
        };
      };
    };
  };
  save: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PeptideoDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PeptideoDTO"];
        };
      };
    };
  };
  findAll_2: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrganismoDTO"][];
        };
      };
    };
  };
  create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganismoDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrganismoDTO"];
        };
      };
    };
  };
  findAll: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PublicacaoDTO"][];
        };
      };
    };
  };
  findById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PublicacaoDTO"];
        };
      };
    };
  };
  delete: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  findByTipoPeptideo: {
    parameters: {
      path: {
        tipoPeptideo: "SINTETIZADO" | "NATURAL";
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PeptideoDTO"][];
        };
      };
    };
  };
  query: {
    parameters: {
      query?: {
        especie?: string;
        familia?: string;
        origem?: string;
        nomeCientifico?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrganismoDTO"][];
        };
      };
    };
  };
  findAll_3: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["NomePopularDTO"][];
        };
      };
    };
  };
  findById_3: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["NomePopularDTO"];
        };
      };
    };
  };
  delete_3: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  findAll_4: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["FuncBiologicaDTO"][];
        };
      };
    };
  };
  findById_4: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["FuncBiologicaDTO"];
        };
      };
    };
  };
  delete_4: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  findAll_5: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CasoSucessoDTO"][];
        };
      };
    };
  };
  findById_5: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CasoSucessoDTO"];
        };
      };
    };
  };
  delete_5: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  findAll_6: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CaracterisAdicionaisDTO"][];
        };
      };
    };
  };
  findById_6: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CaracterisAdicionaisDTO"];
        };
      };
    };
  };
  delete_6: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  findAll_7: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AtivCitotoxicaDTO"][];
        };
      };
    };
  };
  findById_7: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AtivCitotoxicaDTO"];
        };
      };
    };
  };
  delete_7: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  findAll_8: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AtivAntifungicaDTO"][];
        };
      };
    };
  };
  findById_8: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  delete_8: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  findAll_9: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AtivAntibacterianaDTO"][];
        };
      };
    };
  };
  findById_9: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AtivAntibacterianaDTO"];
        };
      };
    };
  };
  delete_9: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
}
